FROM node:22-alpine AS builder
WORKDIR /app

# ✅ 1. Copiamos SOLO los package.json
COPY package.json package-lock.json ./

# ✅ 2. Instalamos (Docker guardará esto y no lo volverá a hacer a menos que instales una librería nueva)
RUN npm install

# ✅ 3. AHORA copiamos el resto de tu código (Tus componentes, hooks, pages, etc.)
COPY . .

# 4. Construimos
RUN npm run build

# ... aquí sigue tu configuración normal de nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
